fix: px-3033 allow vercel environment protection to be configured
mach-composer/mach-composer-plugin-vercel pull request #10
Opened 2023-09-07 12:10 UTC by Jeffrey-Zutt

Allow vercel environment protection to be configured through project_config

2023-09-07 12:59 UTC, demeyerthom requested changes
We also need to add the new fields to the schema at `internal/schemas/site-config.json` otherwise mach-composer will not recognize the new fields

2023-09-07 12:59 UTC, demeyerthom commented on internal/config.go
> +	ProtectWithPassword           string                       `mapstructure:"protect_with_password"`
I think it would be a bit cleaner to adhere to the same data model as the provider here.

So password_protection.password and password_protection.protect_production. We can structure the data the same way as is done with GitRepository (so a separate struct with the fields)

I feel like the same should go for vercel_authentication (so vercel_authentication.protect_production), preferably as a separate object from password_protection. 

This would keep the data models a bit cleaner, and makes adding future fields to either of these objects a bit easier

2023-09-07 12:59 UTC, demeyerthom commented on internal/config.go
> +	ProtectWithPassword           string                       `mapstructure:"protect_with_password"`
So as the following:

`PasswordProtection  PasswordProtection `mapstructure:"password_protection"`

With the following underlying struct:

```
PasswordProtection struct {
  Password string `mapstructure:"password"`
  ProtectProduction bool `mapstructure:"protect_production"`
}
```

2023-09-07 12:59 UTC, demeyerthom commented on internal/plugin.go
> +			{{ renderProperty "password" .ProjectConfig.ProtectWithPassword }}
Depending on my previous comment these then also need changing

2023-09-07 13:45 UTC, Jeffrey-Zutt commented on internal/config.go
> +	ProtectWithPassword           string                       `mapstructure:"protect_with_password"`
Yes I agree, thanks :-).
Made the changes.

2023-09-07 13:45 UTC, Jeffrey-Zutt commented on internal/plugin.go
> +			{{ renderProperty "password" .ProjectConfig.ProtectWithPassword }}
Yes I agree, thanks :-).
Made the changes.

2023-09-07 17:51 UTC, blurrah commented
One thing that makes this differ from the other project config variables is that this can only be set on a site config level right now. I’d prefer if we keep the inheritance in place to keep it consistent. Maybe we’d need to drop that in the future and use more aptly named config types to only allow inheritance for certain fields.

Is that something you’re able to add? Thanks for picking it up, I thought a version rollback of the provider would be enough to not destroy the password protection but guess that’s not the case

2023-09-11 09:17 UTC, okkevandereijk approved these changes

2023-09-11 09:18 UTC, merged